/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author martinez
 */
public class pnlAlbumes extends javax.swing.JPanel {

    /**
     * Creates new form pnlAlbumes
     */
    public pnlAlbumes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Albumes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 45, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/voy por el sueño de muchos.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 88, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/antes de que amanezca.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 88, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24-7.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 88, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/matando lo que soy.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 88, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Voy por el sueño de muchos");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 180, 80, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Rap");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 202, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Antes de que amanezca");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 180, 80, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Pop, country");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 202, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("24/7");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Pop, Pop-rock");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 202, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Matando lo que soy");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 180, 80, -1));

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Rap");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 202, 80, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sm.jpg"))); // NOI18N
        jLabel14.setText("jLabel2");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 247, 80, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Shit masiva");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 339, 80, -1));

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Rap");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 361, 80, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText(" Blacc Hollywood");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 339, 80, -1));

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Rap");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 361, 80, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Blacc Hollywood.jpeg"))); // NOI18N
        jLabel19.setText("jLabel2");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 247, 80, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Romance");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 339, 80, -1));

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Pop");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 361, 80, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/romance.jpg"))); // NOI18N
        jLabel22.setText("jLabel2");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 247, 80, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("The album");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 339, 80, -1));

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Hip Hop, Pop");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 361, 80, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/the album.jpg"))); // NOI18N
        jLabel25.setText("jLabel2");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 247, 80, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
