/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import dtos.UsuarioDTO;
import java.awt.Component;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ui.manager.SessionManager;

/**
 *
 * @author martinez
 */
public class pnlPerfil extends javax.swing.JPanel {
    /**
     * Creates new form Profile
     */
    public pnlPerfil() {
        initComponents();
        if(SessionManager.isLogueado()){
            lblCorreo.setText(SessionManager.getUsuarioActual().getCorreo());
            lblNombre.setText(SessionManager.getUsuarioActual().getNombre());
            try {
                URL imageUrl = new URL(SessionManager.getUsuarioActual().getImagenPath());
                ImageIcon imageIcon = new ImageIcon(imageUrl);
                lblPicture.setIcon(imageIcon);
            } 
            catch (Exception e) {
                e.printStackTrace();
                lblPicture.setText("Imagen no disponible");
                lblPicture.setHorizontalAlignment(JLabel.CENTER);
            }
            lblPicture.setHorizontalAlignment(JLabel.LEFT);
            lblPicture.setAlignmentX(Component.LEFT_ALIGNMENT);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPicture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        btnEditarDatos = new javax.swing.JButton();

        setBackground(new java.awt.Color(246, 246, 246));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.jpg"))); // NOI18N
        add(lblPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/estadisticas.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(86, 140, 186));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 450, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Estadisticas");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        lblCorreo.setBackground(new java.awt.Color(246, 246, 246));
        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lblCorreo.setText("emailhere@example.com");
        lblCorreo.setBorder(null);
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Sesion actual:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, -1));

        lblNombre.setBackground(new java.awt.Color(246, 246, 246));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblNombre.setText("Name here");
        lblNombre.setBorder(null);
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 450, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/morat.jpg"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 90, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/yoss-bones.jpeg"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 90, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/big time rush.jpeg"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ckan.jpeg"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 90, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sm.jpg"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 90, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Lo mas sonado en tu perfil");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, -1));

        lblCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        lblCerrarSesion.setText("Cerrar sesion");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });
        add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        btnEditarDatos.setBackground(new java.awt.Color(0, 0, 0));
        btnEditarDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDatos.setText("Editar");
        btnEditarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarDatosMouseClicked(evt);
            }
        });
        add(btnEditarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        // TODO add your handling code here:
        SessionManager.cerrarSesion();
        JOptionPane.showMessageDialog(this, "Cierre de sesión exitoso");
        OccamyMusic occamy = new OccamyMusic();
        ((OccamyMusic)SwingUtilities.getWindowAncestor(this)).dispose();
        occamy.setVisible(true);
        
//        ((OccamyMusic)SwingUtilities.getWindowAncestor(this)).setLogged(false);
//        JOptionPane.showMessageDialog(this, "Cierre de sesión exitoso");
//        OccamyMusic mainFrame = (OccamyMusic) SwingUtilities.getWindowAncestor(this);
//        mainFrame.switchPanel("Login");
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void btnEditarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarDatosMouseClicked
        // TODO add your handling code here:
        frmActualizar datos = new frmActualizar();
        datos.setVisible(true);
    }//GEN-LAST:event_btnEditarDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JTextField lblCorreo;
    private javax.swing.JTextField lblNombre;
    private javax.swing.JLabel lblPicture;
    // End of variables declaration//GEN-END:variables
}
